# Generated by Django 6.0.3 on 2026-04-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='eventos/')),
                ('fecha_evento', models.DateTimeField()),
                ('activo', models.BooleanField(default=True, help_text='Mostrar u ocultar el contador en la página principal')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
