# Generated by Django 6.0.3 on 2026-04-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventolateral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventodestacado',
            old_name='titulo',
            new_name='titulo_principal',
        ),
        migrations.AddField(
            model_name='eventodestacado',
            name='posicion_imagen',
            field=models.CharField(choices=[('center', 'Centro'), ('top', 'Arriba'), ('bottom', 'Abajo')], default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='eventodestacado',
            name='titulo_superior',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventodestacado',
            name='activo',
            field=models.BooleanField(default=True, help_text='Mostrar u ocultar el evento'),
        ),
    ]
