# Generated by Django 6.0.3 on 2026-04-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ministerio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoMinisterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ministerio')),
            ],
        ),
    ]
