# Generated by Django 6.0.3 on 2026-04-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
