# Generated by Django 6.0.3 on 2026-04-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tiposervicio_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('info', 'Informativo')], default='info', max_length=20)),
                ('color_fondo', models.CharField(default='#ffffff', max_length=20)),
                ('color_texto', models.CharField(default='#000000', max_length=20)),
                ('color_boton', models.CharField(default='#6a0dad', max_length=20)),
                ('texto_boton', models.CharField(default='Entendido', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
    ]
