# Generated by Django 6.0.3 on 2026-04-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aviso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='color_boton',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='color_fondo',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='color_texto',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='fecha_inicio',
        ),
        migrations.AlterField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('informativo', 'Informativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
