# Generated by Django 6.0.3 on 2026-04-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_eventodestacado_color_contador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventodestacado',
            name='color_contador',
            field=models.CharField(default='#ffffff', help_text='Color de los números del contador', max_length=7),
        ),
        migrations.AlterField(
            model_name='eventodestacado',
            name='color_subtitulo',
            field=models.CharField(default='#cbf5e4', help_text='Color del subtítulo', max_length=7),
        ),
        migrations.AlterField(
            model_name='eventodestacado',
            name='color_titulo',
            field=models.CharField(default='#f6ff00', help_text='Color del título principal', max_length=7),
        ),
    ]
