# Generated by Django 6.0.3 on 2026-04-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_eventodestacado_color_contador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='tipo_fondo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], default='imagen', max_length=10),
        ),
        migrations.AddField(
            model_name='hero',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='hero/videos/'),
        ),
    ]
