# Generated by Django 6.0.3 on 2026-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_hero_tipo_fondo_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodestacado',
            name='imagen_movil',
            field=models.ImageField(blank=True, help_text='Imagen optimizada para celulares (opcional)', null=True, upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='eventodestacado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventodestacado',
            name='color_contador',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='eventodestacado',
            name='color_subtitulo',
            field=models.CharField(default='#cbf5e4', max_length=7),
        ),
        migrations.AlterField(
            model_name='eventodestacado',
            name='color_titulo',
            field=models.CharField(default='#f6ff00', max_length=7),
        ),
    ]
