# Generated by Django 6.0.3 on 2026-04-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_eventodestacado_imagen_movil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventolateral',
            options={'ordering': ['orden', 'fecha'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='eventolateral',
            name='categoria',
            field=models.CharField(choices=[('Servicio', 'Servicio'), ('Retiro', 'Retiro'), ('Conferencia', 'Conferencia'), ('Taller bíblico', 'Taller bíblico'), ('Congreso', 'Congreso'), ('Campamento', 'Campamento'), ('Otro', 'Otro')], default='Servicio', max_length=50),
        ),
        migrations.AddField(
            model_name='eventolateral',
            name='fecha',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventolateral',
            name='hora',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
