# Generated by Django 6.0.3 on 2026-05-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_eventolateral_options_eventolateral_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventodestacado',
            name='fecha_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
