# Generated by Django 6.0.3 on 2026-05-01 20:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_eventolateral_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventodestacado',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagen PC'),
        ),
        migrations.AlterField(
            model_name='eventodestacado',
            name='imagen_movil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen celular'),
        ),
    ]
