# Generated by Django 6.0.3 on 2026-05-01 20:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_eventodestacado_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministerio',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagen perfil'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='portada',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagen portada'),
        ),
    ]
