# Generated by Django 6.0.3 on 2026-05-01 20:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_ministerio_imagen_alter_ministerio_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='para moviles'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='hero/videos/', verbose_name='para pc'),
        ),
    ]
