# Generated by Django 5.2.4 on 2026-05-04 20:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_aviso_id_alter_eventodestacado_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Video PC'),
        ),
    ]
